#!/bin/bash

# exit on error
set -e

kdialog --passivepopup "Converting "$1 1

# original size
size_o=`du -h $1 | cut -f1`
# transcode with ffmpeg
eval "ffmpeg -hwaccel cuda -i "$1" -c:v hevc_nvenc -c:a libopus -crf 26 "$1".opt.mp4"
# size after transcoding
size_a=`du -h $1.opt.mp4 | cut -f1`


kdialog --yesno $size_o" => "$size_a"\nAre you sure?"
if [[ $? -ne 0 ]] ; then
    exit 0
fi

# replace
trash $1
mv $1".opt.mp4" $1
kdialog --passivepopup "Done" 1
