#!/bin/bash

c=`ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=noprint_wrappers=1:nokey=1 "$1"`
if [[ $c == "hevc"  ]]
then
    kdialog --passivepopup "Codec is HEVC already."
    exit 1
fi

# exit on error
set -e

kdialog --passivepopup "Converting "$1 1

# original size
size_o=`du -h $1 | cut -f1`
# transcode with ffmpeg
eval "ffmpeg -hwaccel cuda -i \""$1"\" -c:v hevc_nvenc -c:a libopus -crf 26 \""$1"\.opt.mp4\""
# size after transcoding
size_a=`du -h $1.opt.mp4 | cut -f1`


kdialog --yesno $size_o" => "$size_a"\nAre you sure?"
if [[ $? -ne 0 ]] ; then
    exit 0
fi

# replace
trash $1
mv $1".opt.mp4" $1
kdialog --passivepopup "Done" 1
