#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo "No specified file."
    exit 1
fi

set -e

ls -lh $1

echo "ffpb -hwaccel cuda -i "$1" -c:v hevc_nvenc -c:a libopus -crf 26 "$1".opt.mp4"
eval "ffpb -hwaccel cuda -i "$1" -c:v hevc_nvenc -c:a libopus -crf 26 "$1".opt.mp4"

ls -lh $1".opt.mp4"

read -p "Are you sure? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    trash $1
    mv $1".opt.mp4" $1
fi
